name: Build ENet for LÖVE2D
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cmake-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    # Install CMake
    - name: Install CMake
      run: choco install cmake
    
    # Configure CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    # Build ENet
    - name: Build ENet
      run: cmake --build build --config Release
    
    # Find the DLL
    - name: Find DLL location
      run: |
        echo "Looking for the ENet DLL..."
        dir /s build\*.dll
        echo "=========="
        dir /s *.dll
      shell: cmd
    
    # Upload the DLL as artifact (using a more flexible path)
    - name: Upload ENet DLL
      uses: actions/upload-artifact@v4
      with:
        name: enet-dll
        path: |
          build/**/*.dll
          build/Release/*.dll
          build/bin/Release/*.dll
        if-no-files-found: warn
