name: Build ENet for LÖVE2D
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-enet:
    runs-on: windows-latest
    steps:
    # Checkout your repository
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # Clone the ENet repository
    - name: Clone ENet Repository
      run: git clone https://github.com/lsalzman/enet.git
    
    # Setup Visual Studio environment
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    # Configure and build ENet using CMake
    - name: Configure and Build ENet
      run: |
        cd enet
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
        cmake --build . --config Release
    
    # List all files to see what was produced
    - name: List output files
      run: |
        echo "Listing all files in enet/build directory..."
        dir /s enet\build\*.*
      shell: cmd
    
    # Upload all potential DLL files and additional outputs
    - name: Upload ENet outputs
      uses: actions/upload-artifact@v4
      with:
        name: enet-build-outputs
        path: |
          enet/build/**/*.dll
          enet/build/**/*.lib
          enet/build/Release/*.dll
          enet/build/Release/*.lib
          enet/build/bin/Release/*.dll
          enet/build/**/*.so
        if-no-files-found: warn
