name: Build ENet with CMake

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cmake-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install CMake and build tools
      run: |
        choco install cmake # Für Windows
        sudo apt-get install cmake g++ make # Für Linux

    # Konfiguriere CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    # Baue ENet
    - name: Build ENet
      run: cmake --build build --config Release

    # Lade die DLL als Artefakt hoch
    - name: Upload ENet DLL
      uses: actions/upload-artifact@v3
      with:
        name: enet-dll
        path: build/bin/enet.dll
